name: Feature Request
description: Suggest a new feature for AI Search Schema
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        機能提案ありがとうございます！

        Note: Feature requests are tracked but implementation is not guaranteed.
        機能要望は記録しますが、実装を保証するものではありません。

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false

  - type: dropdown
    id: schema-type
    attributes:
      label: Related Schema Type
      description: Which schema type is this related to?
      options:
        - Organization
        - LocalBusiness
        - Article
        - FAQPage
        - Product
        - BreadcrumbList
        - llms.txt
        - Other
    validations:
      required: false
